service: yebox-api-engine
useDotenv: true

frameworkVersion: "2"

provider:
   name: aws
   runtime: nodejs14.x
   lambdaHashingVersion: 20201221
   memorySize: 130
   timeout: 10
   stage: ${opt:stage, 'dev'}
   region: eu-west-1

functions:
   api:
      handler: handler.api
      events:
         - http: ANY /
         - http: ANY /{proxy+}

plugins:
   - serverless-offline
